title: "Faraz Heravi"
description: "portfolio"
email: "farazh [at] utexas [dot] edu"
linkedin: "https://linkedin.com/in/farazheravi"
github: "https://github.com/fheravi"
headshot: "/assets/headshot.png"
markdown: kramdown